[build]
  command = "pnpm build"
  publish = "dist/"

[[redirects]]
  from = "/guidelines"
  to = "/conduct"

[[redirects]]
  from = "/tmir"
  to = "https://tmir.transistor.fm/"
  status = 302
  force = true
